spring:
    profiles: dev
elasticsearch:
    rest:
        uris: 172.17.208.236:9200
        username: ww
        password: ww

myjdbc:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cow8.cn:3306/javajdbc?characterEncoding=UTF-8&serverTimezone=UTC
    dbname: javajdbc
    acc: root
    pwd: wo1274haoba
kafka:
    bootstrap_servers: 127.0.0.1:9092
    producer:
        key_serializer: org.apache.kafka.common.serialization.StringSerializer
        value_serializer: org.apache.kafka.common.serialization.StringSerializer
        retries: 0 # 失败重试次数
        batch_size: 16384
        buffer_memory: 33554432
        acks: -1 # 取值 all, -1, 0, 1
    consumer:
        enable_auto_commit: true
        auto_commit_interval: 5000
        group_id: live_service
        auto_offset_reset: latest # 消费offset取值earliest,latest,none（默认：latest）
        key_deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value_deserializer: org.apache.kafka.common.serialization.StringDeserializer
    template:
        default_topic: mytest
logging:
    config: classpath:log4j2-dev.xml